spring:
  config:
    activate:
      on-profile: prod

  liquibase:
      change-log: classpath:db/changelog/db.changelog-master.yaml

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  datasource:
    url: ${DB_URL_PROD}
    driver-class-name: org.postgresql.Driver
    username: ${DB_USER_PROD}
    password: ${DB_PWD_PROD}